import HermesMemory.MemoryDynamics
import HermesMemory.StrengthDecay
import HermesMemory.SoftSelection
import HermesMemory.NoveltyBonus
import HermesMemory.ComposedSystem
import HermesMemory.ContractionWiring
